language: c

dist: xenial

jobs:
  fast_finish: true
  include:
    - env: USING_AUTOTOOLS=yes
      addons:
        apt:
          packages: [libsndfile-dev, libfftw3-dev, libasound2-dev,  autoconf, automake-1.15, pkg-config, m4]
      script:
        - ./autogen.sh && ./configure --enable-sndfile --enable-alsa && make distcheck
        - cat src/config.h

addons:
  apt:
    packages: [libsndfile-dev, libfftw3-dev, libasound2-dev]

env:
  - CMAKE_SHARED=OFF BUILD_TYPE=Debug
  - CMAKE_SHARED=ON BUILD_TYPE=Debug
  - CMAKE_SHARED=OFF BUILD_TYPE=Release
  - CMAKE_SHARED=ON BUILD_TYPE=Release

script:
  - mkdir build
  - cd build
  - cmake -DBUILD_SHARED_LIBS=$CMAKE_SHARED -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_FLAGS="-Wall -Wextra -Werror" ..
  - cat config.h
  - make && make test
